In [1]:
#Q1

In [3]:
import numpy as np
list_ = [ '1' , '2','3','4','5']
array_list = np.array(object = list_)

In [4]:
list_

['1', '2', '3', '4', '5']

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [13]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

In [8]:
#Q2

In [14]:
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [15]:
#Q3

In [16]:
array_list = np.array(object = list_, dtype = int)

In [17]:
array_list

array([1, 2, 3, 4, 5])

In [18]:
array_list.dtype

dtype('int64')

In [20]:
type(list_)

list

In [22]:
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [21]:
#Q4

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [25]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
num_array.shape

(2, 3)

In [27]:
num_array.size

6

In [29]:
#Q5

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
import numpy.matlib as nm

In [33]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])